# This script is for setting the environment required to build (and maybe run?) gen_domain.
#
# It has been modified from the autogenerated file in
# ./src/.env_mach_specific.sh, in order to solve problems with overzealous
# purging of modules, destroying the existing PATH, and loading modules in the wrong order.

source /cluster/installations/lmod/lmod/init/profile
module purge 
module load netCDF-Fortran/4.4.4-intel-2018a-HDF5-1.8.19
export PATH=/cluster/projects/nn9188k/janko/miniconda3/condabin:/cluster/home/janko/bin:/node/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/cluster/bin:/cluster/home/janko/.local/bin:/cluster/home/janko/cesm/cesm2.1.2-git/cime/scripts:/cluster/home/janko/cesm/cesm2.1.2-git/cime/scripts/Tools:/cluster/home/janko/cesm/cesm2.1.2-git/cime/scripts:/cluster/home/janko/cesm/cesm2.1.2-git/cime/scripts:${PATH}
export OMP_STACKSIZE=256M
export NETCDF_PATH=/cluster/software/netCDF/4.4.1.1-intel-2018a-HDF5-1.8.19
export COMPILER=intel
export MPILIB=mpi-serial
export DEBUG=FALSE
export OS=LINUX

# To build gen_domain, not just set the domain, run the script
# jik_build_gen_domain.sh. It just calls this script to set the environment,
# changes to the src subdirectory, and calls gmake.